SYSTEM_APPLICATION_NAME: 'Bar Code Reader'
ADMIN_EMAIL: barcode@yopmail.com
FROM_EMAIL: barcode@yopmail.com
TELEPHONE: '9887712781'
ADMIN_PAGE_LIMIT: '20'
ADMIN_DATE_FORMAT: 'd F, Y'
ADMIN_DATE_TIME_FORMAT: 'd F, Y H:i A'
ADDRESS: '6-Kha-9, Jawahar Nagar, Kota'
SMTP_ALLOW: '1'
SMTP_EMAIL_HOST: mail.24livehost.com
SMTP_USERNAME: wwwsmtp@24livehost.com
SMTP_PASSWORD: 'dsmtp807#'
SMTP_PORT: '25'
SMTP_TLS: '1'
MAIN_FAVICON: iCIVQBehJgegsqBSYv7c5sHcPM8lX7hJQ1cMM4BB.png
MAIN_LOGO: SHcJZCKHnRSYUqndYaiwK84rlwGr3OatzVdFoIOm.png
copyrighttext: 'Copyright @ 2020 |  All rights reserved'
gold-price: '50000 per gram'
